### ISSUE TITLE
Criar script para gerar um README.md direto da página do PUG-PE.

### ISSUE THREAD

**Issue by heliomeiralins** [pugpe/encontros-palestras#2]
- Adicionar `requirements.txt` ou usar um poetry da vida.
- `$ python pug.py LXV (ou 65)` -> Cria readme em `2020/65/` seguindo o modelo de #1 
Deve puxar descrição, data, hora, local e palestras da página.

Opcional:
adicionar uma entrada no readme.md da raiz do projeto com o link pro README gerado.

**Comment by andersonberg** [comment]
Eu vou adicionar o código do spider que eu usei na LT do PUG 65, já pode ajudar nessa issue
